modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "dungeons_iso"
version = "${version}"
displayName = "Dungeons Perspective"
authors = "cleannrooster/Forg"
description = '''
Changes Minecraft's perspective to be more like Minecraft Dungeons.
'''
logoFile = "assets/dungeons_iso/icon.png"

[[dependencies.dungeons_iso]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dungeons_iso]]
modId = "sodium"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.dungeons_iso]]
modId = "owo"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.dungeons_iso]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.dungeons_iso]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "dungeons_iso.mixins.json"
